[programs.localnet]
solstory = "storyXpLfG5mZckpXWqKF8F2fQJfj8bCpFvNwHjiHqa"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/juliamerz/.config/solana/devent.json"

[scripts]
test = "ts-mocha -p ./api/tsconfig-base.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"

[test]
startup_wait = 20000

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"

[[test.validator.clone]]
address = "p1exdMJcjVao65QdewkaZRUnU6VPSXhus9n2GzWfh98"


[[test.validator.clone]]
address = "PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT"


