
import {Program} from '@project-serum/anchor';
// import * as solstory from './solstory.json'

const SOLSTORY_PUBKEY = "storyXpLfG5mZckpXWqKF8F2fQJfj8bCpFvNwHjiHqa"

/**
 * Create an anchor autogenerated IDL.
 **/
// export const solstoryProgram = new Program(solstory, SOLSTORY_PUBKEY)
