
import {Program} from '@project-serum/anchor';
// import * as solstory from './solstory.json'

const SOLSTORY_PUBKEY = "H3iPPJ6td4XPAVmBsygE8NxjnmAgeafPktr59JiV4jAv"

/**
 * Create an anchor autogenerated IDL.
 **/
// export const solstoryProgram = new Program(solstory, SOLSTORY_PUBKEY)
